name: Go-Backend-Poker Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.12.1"

      - name: Set env
        run: export PATH="$PATH:$HOME/.local/bin"

      - name: check protoc version
        run: protoc --version

      - name: Installing protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

      - name: Installing protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Set env for protoc
        run: export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Check go env
        run: go env GOPATH

      - name: Build
        run: go build -v ./...

      # - name: Gotestsum installer
      #   run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: go test -v  -short ./...
